export type Project = {
  id: string;
  slug: string;
  title: string;
  description: string;
  tech: string[];
  image: string;
  liveUrl?: string;
  codeUrl?: string;
  problem?: string;
  solution?: string;
  features?: string[];
  lessons?: string;
  featured?: boolean;
  selected?: boolean;
  tagline?: string;
  year?: string;
  role?: string;
  architecture?: string;
  experiment?: boolean;
  category?: string;
  quarter?: string;
  metrics?: { value: string; label: string }[];
  screenshots?: { src: string; alt: string }[];
};
